### ISSUE TITLE
It there a way to set range?

### ISSUE THREAD

**Issue by janakagamini** [ashik94vc/ElegantNumberButton#2]
Is there a built in method to set min and max acceptable values.

Use case: I want users to only be able to select values between 1 and 5.

**Comment by ashik94vc** [comment]
Will add it

**Comment by ashik94vc** [comment]
Added Check Latest Commit

**Comment by janakagamini** [comment]
@ashik94vc Thanks for the quick response.

I set both `initialNumber=1` and `finalNumber=5` in my layout xml, and use `setRange(1, 5)` in Java code, yet it has no effect. I can select-minus all the way to 0 and select-plus to numbers greater than 5.

**Comment by ashik94vc** [comment]
Will look into it.

**Comment by ashik94vc** [comment]
Cannot be reproduced
