### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by saikrishna7789** [ashik94vc/ElegantNumberButton#33]
![Screenshot 2020-04-07 at 1 08 27 PM](https://user-images.githubusercontent.com/40738197/78643019-3d4a5100-78d1-11ea-9381-8de8c0da5ef0.png)

**Comment by markrizkalla** [comment]
Put .bridge at the end of you parent app them

**Comment by saikrishna7789** [comment]
Thank You buddy. Its Working fine Now @markrizkalla
