### ISSUE TITLE
Ripple effect on button needed 

### ISSUE THREAD

**Issue by LOG-TAG** [ashik94vc/ElegantNumberButton#7]
Ripple effect option on button needed  for best UX!

**Comment by ashik94vc** [comment]
Hey,

I am skeptical about that. I am not sure if the ripple should cover the whole component or just the button.

**Comment by ashik94vc** [comment]
Ripple won't be an eye candy since the button has 2 independent clickable areas

**Comment by LOG-TAG** [comment]
left to right or right to left ripple will work!
